name: splitwise_clone
version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: splitwise_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/splitwise_db

volumes:
  postgres_data:
