name: splitwise_clone
version: "3.8"
services:
  # Only database in Docker for development
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: splitwise_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Add healthcheck for better development experience
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
